// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeiaCraftsInfrastructure.Data;

#nullable disable

namespace WeiaCraftsInfrastructure.Migrations
{
    [DbContext(typeof(WeiaCraftsContext))]
    partial class WeiaCraftsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourseTrainee", b =>
                {
                    b.Property<int>("EnrolledCoursesId")
                        .HasColumnType("int");

                    b.Property<string>("EnrolledTraineesUserName")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EnrolledCoursesId", "EnrolledTraineesUserName");

                    b.HasIndex("EnrolledTraineesUserName");

                    b.ToTable("CourseTrainee");
                });

            modelBuilder.Entity("CourseTrainee1", b =>
                {
                    b.Property<int>("CompletedCoursesId")
                        .HasColumnType("int");

                    b.Property<string>("CompletedTraineesUserName")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CompletedCoursesId", "CompletedTraineesUserName");

                    b.HasIndex("CompletedTraineesUserName");

                    b.ToTable("TraineeCompletedCourses", (string)null);
                });

            modelBuilder.Entity("CourseTrainee2", b =>
                {
                    b.Property<int>("FavoriteCoursesId")
                        .HasColumnType("int");

                    b.Property<string>("FavoritedByTraineesUserName")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("FavoriteCoursesId", "FavoritedByTraineesUserName");

                    b.HasIndex("FavoritedByTraineesUserName");

                    b.ToTable("TraineeFavoriteCourses", (string)null);
                });

            modelBuilder.Entity("WeiaCraftsDomain.Entities.AccountStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AccountStatuses");
                });

            modelBuilder.Entity("WeiaCraftsDomain.Entities.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ChatbotUpdates")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Permissions")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PlatformPolicies")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ThirdPartyIntegrations")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("WeiaCraftsDomain.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("WeiaCraftsDomain.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("CourseId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("WeiaCraftsDomain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("WeiaCraftsDomain.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessType")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CoverImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsKidFriendly")
                        .HasColumnType("bit");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("PromoVideoURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("RatingCount")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrainerUserName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("WideRangeCategory")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TrainerUserName");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("WeiaCraftsDomain.Entities.CourseMaterial", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int?>("LessonId")
                        .HasColumnType("int");

                    b.HasKey("CourseId", "MaterialId");

                    b.HasIndex("LessonId");

                    b.HasIndex("MaterialId");

                    b.ToTable("CourseMaterials");
                });

            modelBuilder.Entity("WeiaCraftsDomain.Entities.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastAccessedLessonId")
                        .HasColumnType("int");

                    b.Property<double>("PercentageCompleted")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("LastAccessedLessonId");

                    b.HasIndex("UserId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("WeiaCraftsDomain.Entities.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FeedbackType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("TraineeUserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("picturePath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TraineeUserName");

                    b.ToTable("Feedbacks");

                    b.HasDiscriminator<string>("FeedbackType").HasValue("Feedback");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("WeiaCraftsDomain.Entities.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContentType")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId", "SequenceOrder")
                        .IsUnique();

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("WeiaCraftsDomain.Entities.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("WeiaCraftsDomain.Entities.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("RatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RatingType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("TraineeUserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("TraineeUserName");

                    b.ToTable("Ratings");

                    b.HasDiscriminator<string>("RatingType").HasValue("Rating");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("WeiaCraftsDomain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("WeiaCraftsDomain.Entities.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PaidAccountTraineeUserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubscriptionEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SubscriptionStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubscriptionTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaidAccountTraineeUserName");

                    b.HasIndex("SubscriptionTypeId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("WeiaCraftsDomain.Entities.SubscriptionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionTypes");
                });

            modelBuilder.Entity("WeiaCraftsDomain.Entities.TrainerAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrainerUserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("TrainerUserName");

                    b.ToTable("TrainerAlerts");
                });

            modelBuilder.Entity("WeiaCraftsDomain.Entities.User", b =>
                {
                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("AccountStatusId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("RegisterationDate")
                        .HasColumnType("date");

                    b.HasKey("UserName");

                    b.HasIndex("AccountStatusId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasDiscriminator().HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("WeiaCraftsDomain.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssignedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserName", "RoleId")
                        .IsUnique();

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("WeiaCraftsDomain.Entities.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("CourseFeedback", b =>
                {
                    b.HasBaseType("WeiaCraftsDomain.Entities.Feedback");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.HasIndex("CourseId");

                    b.HasDiscriminator().HasValue("Course");
                });

            modelBuilder.Entity("PlatformFeedback", b =>
                {
                    b.HasBaseType("WeiaCraftsDomain.Entities.Feedback");

                    b.Property<string>("PlatformArea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Platform");
                });

            modelBuilder.Entity("TrainerFeedback", b =>
                {
                    b.HasBaseType("WeiaCraftsDomain.Entities.Feedback");

                    b.Property<string>("TrainerUserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasIndex("TrainerUserName");

                    b.HasDiscriminator().HasValue("Trainer");
                });

            modelBuilder.Entity("VideoFeedback", b =>
                {
                    b.HasBaseType("WeiaCraftsDomain.Entities.Feedback");

                    b.Property<int>("VideoId")
                        .HasColumnType("int");

                    b.HasIndex("VideoId");

                    b.HasDiscriminator().HasValue("Video");
                });

            modelBuilder.Entity("TrainerRating", b =>
                {
                    b.HasBaseType("WeiaCraftsDomain.Entities.Rating");

                    b.Property<string>("TrainerUserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasIndex("TrainerUserName");

                    b.HasDiscriminator().HasValue("Trainer");
                });

            modelBuilder.Entity("VideoRating", b =>
                {
                    b.HasBaseType("WeiaCraftsDomain.Entities.Rating");

                    b.Property<int>("VideoId")
                        .HasColumnType("int");

                    b.HasIndex("VideoId");

                    b.HasDiscriminator().HasValue("Video");
                });

            modelBuilder.Entity("WeiaCraftsDomain.Entities.CourseRating", b =>
                {
                    b.HasBaseType("WeiaCraftsDomain.Entities.Rating");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.HasIndex("CourseId");

                    b.HasDiscriminator().HasValue("Course");
                });

            modelBuilder.Entity("WeiaCraftsDomain.Entities.Trainee", b =>
                {
                    b.HasBaseType("WeiaCraftsDomain.Entities.User");

                    b.Property<int>("RewardPoints")
                        .HasColumnType("int");

                    b.Property<int>("TraineeId")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Trainee");
                });

            modelBuilder.Entity("WeiaCraftsDomain.Entities.Trainer", b =>
                {
                    b.HasBaseType("WeiaCraftsDomain.Entities.User");

                    b.Property<bool>("IsAlsoTrainee")
                        .HasColumnType("bit");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("RatingCount")
                        .HasColumnType("int");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Trainer");
                });

            modelBuilder.Entity("WeiaCraftsDomain.Entities.PaidAccountTrainee", b =>
                {
                    b.HasBaseType("WeiaCraftsDomain.Entities.Trainee");

                    b.Property<int?>("CurrentSubscriptionId")
                        .HasColumnType("int");

                    b.HasIndex("CurrentSubscriptionId");

                    b.HasDiscriminator().HasValue("PaidAccountTrainee");
                });

            modelBuilder.Entity("CourseTrainee", b =>
                {
                    b.HasOne("WeiaCraftsDomain.Entities.Course", null)
                        .WithMany()
                        .HasForeignKey("EnrolledCoursesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeiaCraftsDomain.Entities.Trainee", null)
                        .WithMany()
                        .HasForeignKey("EnrolledTraineesUserName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourseTrainee1", b =>
                {
                    b.HasOne("WeiaCraftsDomain.Entities.Course", null)
                        .WithMany()
                        .HasForeignKey("CompletedCoursesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeiaCraftsDomain.Entities.Trainee", null)
                        .WithMany()
                        .HasForeignKey("CompletedTraineesUserName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourseTrainee2", b =>
                {
                    b.HasOne("WeiaCraftsDomain.Entities.Course", null)
                        .WithMany()
                        .HasForeignKey("FavoriteCoursesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeiaCraftsDomain.Entities.Trainee", null)
                        .WithMany()
                        .HasForeignKey("FavoritedByTraineesUserName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WeiaCraftsDomain.Entities.Cart", b =>
                {
                    b.HasOne("WeiaCraftsDomain.Entities.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("WeiaCraftsDomain.Entities.Cart", "UserName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("WeiaCraftsDomain.ValueObjects.AmountWithCurrency", "TotalAmount", b1 =>
                        {
                            b1.Property<int>("CartId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("CartId");

                            b1.ToTable("Carts");

                            b1.WithOwner()
                                .HasForeignKey("CartId");
                        });

                    b.Navigation("TotalAmount")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WeiaCraftsDomain.Entities.CartItem", b =>
                {
                    b.HasOne("WeiaCraftsDomain.Entities.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WeiaCraftsDomain.Entities.Course", "Course")
                        .WithMany("CartItems")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsOne("WeiaCraftsDomain.ValueObjects.AmountWithCurrency", "Price", b1 =>
                        {
                            b1.Property<int>("CartItemId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("CartItemId");

                            b1.ToTable("CartItems");

                            b1.WithOwner()
                                .HasForeignKey("CartItemId");
                        });

                    b.Navigation("Cart");

                    b.Navigation("Course");

                    b.Navigation("Price")
                        .IsRequired();
                });

            modelBuilder.Entity("WeiaCraftsDomain.Entities.Course", b =>
                {
                    b.HasOne("WeiaCraftsDomain.Entities.Category", null)
                        .WithMany("Courses")
                        .HasForeignKey("CategoryId");

                    b.HasOne("WeiaCraftsDomain.Entities.Trainer", "Trainer")
                        .WithMany("CreatedCourses")
                        .HasForeignKey("TrainerUserName")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("WeiaCraftsDomain.ValueObjects.AmountWithCurrency", "Price", b1 =>
                        {
                            b1.Property<int>("CourseId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("CourseId");

                            b1.ToTable("Courses");

                            b1.WithOwner()
                                .HasForeignKey("CourseId");
                        });

                    b.Navigation("Price")
                        .IsRequired();

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("WeiaCraftsDomain.Entities.CourseMaterial", b =>
                {
                    b.HasOne("WeiaCraftsDomain.Entities.Course", "Course")
                        .WithMany("CourseMaterials")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WeiaCraftsDomain.Entities.Lesson", null)
                        .WithMany("LessonMaterials")
                        .HasForeignKey("LessonId");

                    b.HasOne("WeiaCraftsDomain.Entities.Material", "Material")
                        .WithMany("CourseMaterials")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("WeiaCraftsDomain.Entities.Enrollment", b =>
                {
                    b.HasOne("WeiaCraftsDomain.Entities.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WeiaCraftsDomain.Entities.Lesson", "LastAccessedLesson")
                        .WithMany()
                        .HasForeignKey("LastAccessedLessonId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("WeiaCraftsDomain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("LastAccessedLesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WeiaCraftsDomain.Entities.Feedback", b =>
                {
                    b.HasOne("WeiaCraftsDomain.Entities.Trainee", "Trainee")
                        .WithMany("Feedbacks")
                        .HasForeignKey("TraineeUserName")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("WeiaCraftsDomain.Entities.Lesson", b =>
                {
                    b.HasOne("WeiaCraftsDomain.Entities.Course", "Course")
                        .WithMany("Lessons")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("WeiaCraftsDomain.Entities.Rating", b =>
                {
                    b.HasOne("WeiaCraftsDomain.Entities.Trainee", "Trainee")
                        .WithMany("Ratings")
                        .HasForeignKey("TraineeUserName")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("WeiaCraftsDomain.Entities.Subscription", b =>
                {
                    b.HasOne("WeiaCraftsDomain.Entities.PaidAccountTrainee", "PaidAccountTrainee")
                        .WithMany("Subscriptions")
                        .HasForeignKey("PaidAccountTraineeUserName")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WeiaCraftsDomain.Entities.SubscriptionType", "SubscriptionType")
                        .WithMany()
                        .HasForeignKey("SubscriptionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("WeiaCraftsDomain.ValueObjects.AmountWithCurrency", "Price", b1 =>
                        {
                            b1.Property<int>("SubscriptionId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("SubscriptionId");

                            b1.ToTable("Subscriptions");

                            b1.WithOwner()
                                .HasForeignKey("SubscriptionId");
                        });

                    b.Navigation("PaidAccountTrainee");

                    b.Navigation("Price")
                        .IsRequired();

                    b.Navigation("SubscriptionType");
                });

            modelBuilder.Entity("WeiaCraftsDomain.Entities.TrainerAlert", b =>
                {
                    b.HasOne("WeiaCraftsDomain.Entities.Trainer", "Trainer")
                        .WithMany("Alerts")
                        .HasForeignKey("TrainerUserName")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("WeiaCraftsDomain.Entities.User", b =>
                {
                    b.HasOne("WeiaCraftsDomain.Entities.AccountStatus", "AccountStatus")
                        .WithMany("Users")
                        .HasForeignKey("AccountStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountStatus");
                });

            modelBuilder.Entity("WeiaCraftsDomain.Entities.UserRole", b =>
                {
                    b.HasOne("WeiaCraftsDomain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WeiaCraftsDomain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserName")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WeiaCraftsDomain.Entities.Video", b =>
                {
                    b.HasOne("WeiaCraftsDomain.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("CourseFeedback", b =>
                {
                    b.HasOne("WeiaCraftsDomain.Entities.Course", "Course")
                        .WithMany("FeedbacksRecieved")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("TrainerFeedback", b =>
                {
                    b.HasOne("WeiaCraftsDomain.Entities.Trainer", "Trainer")
                        .WithMany("FeedbacksReceived")
                        .HasForeignKey("TrainerUserName")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("VideoFeedback", b =>
                {
                    b.HasOne("WeiaCraftsDomain.Entities.Video", "Video")
                        .WithMany("FeedbacksRecieved")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("TrainerRating", b =>
                {
                    b.HasOne("WeiaCraftsDomain.Entities.Trainer", "Trainer")
                        .WithMany("RatingsReceived")
                        .HasForeignKey("TrainerUserName")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("VideoRating", b =>
                {
                    b.HasOne("WeiaCraftsDomain.Entities.Video", "Video")
                        .WithMany("RatingsReceived")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("WeiaCraftsDomain.Entities.CourseRating", b =>
                {
                    b.HasOne("WeiaCraftsDomain.Entities.Course", "Course")
                        .WithMany("RatingsReceived")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("WeiaCraftsDomain.Entities.PaidAccountTrainee", b =>
                {
                    b.HasOne("WeiaCraftsDomain.Entities.Subscription", "CurrentSubscription")
                        .WithMany()
                        .HasForeignKey("CurrentSubscriptionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CurrentSubscription");
                });

            modelBuilder.Entity("WeiaCraftsDomain.Entities.AccountStatus", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("WeiaCraftsDomain.Entities.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("WeiaCraftsDomain.Entities.Category", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("WeiaCraftsDomain.Entities.Course", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("CourseMaterials");

                    b.Navigation("Enrollments");

                    b.Navigation("FeedbacksRecieved");

                    b.Navigation("Lessons");

                    b.Navigation("RatingsReceived");
                });

            modelBuilder.Entity("WeiaCraftsDomain.Entities.Lesson", b =>
                {
                    b.Navigation("LessonMaterials");
                });

            modelBuilder.Entity("WeiaCraftsDomain.Entities.Material", b =>
                {
                    b.Navigation("CourseMaterials");
                });

            modelBuilder.Entity("WeiaCraftsDomain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("WeiaCraftsDomain.Entities.User", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("WeiaCraftsDomain.Entities.Video", b =>
                {
                    b.Navigation("FeedbacksRecieved");

                    b.Navigation("RatingsReceived");
                });

            modelBuilder.Entity("WeiaCraftsDomain.Entities.Trainee", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("WeiaCraftsDomain.Entities.Trainer", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("CreatedCourses");

                    b.Navigation("FeedbacksReceived");

                    b.Navigation("RatingsReceived");
                });

            modelBuilder.Entity("WeiaCraftsDomain.Entities.PaidAccountTrainee", b =>
                {
                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
